//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForm.CtPhieuNhapServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CtPhieuNhapServiceReference.ICtPhieuNhapService1")]
    public interface ICtPhieuNhapService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtPhieuNhapService1/DoWork", ReplyAction="http://tempuri.org/ICtPhieuNhapService1/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtPhieuNhapService1/DoWork", ReplyAction="http://tempuri.org/ICtPhieuNhapService1/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICtPhieuNhapService1Channel : WinForm.CtPhieuNhapServiceReference.ICtPhieuNhapService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CtPhieuNhapService1Client : System.ServiceModel.ClientBase<WinForm.CtPhieuNhapServiceReference.ICtPhieuNhapService1>, WinForm.CtPhieuNhapServiceReference.ICtPhieuNhapService1 {
        
        public CtPhieuNhapService1Client() {
        }
        
        public CtPhieuNhapService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CtPhieuNhapService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CtPhieuNhapService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CtPhieuNhapService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
