//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm.CTDHService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CtDonDH", Namespace="http://schemas.datacontract.org/2004/07/WcfUngDungWeb")]
    [System.SerializableAttribute()]
    public partial class CtDonDH : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float DonGiaDatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaDonDHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SP_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoLuongDatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float DonGiaDat {
            get {
                return this.DonGiaDatField;
            }
            set {
                if ((this.DonGiaDatField.Equals(value) != true)) {
                    this.DonGiaDatField = value;
                    this.RaisePropertyChanged("DonGiaDat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaDonDH {
            get {
                return this.MaDonDHField;
            }
            set {
                if ((object.ReferenceEquals(this.MaDonDHField, value) != true)) {
                    this.MaDonDHField = value;
                    this.RaisePropertyChanged("MaDonDH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SP_ID {
            get {
                return this.SP_IDField;
            }
            set {
                if ((this.SP_IDField.Equals(value) != true)) {
                    this.SP_IDField = value;
                    this.RaisePropertyChanged("SP_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuongDat {
            get {
                return this.SoLuongDatField;
            }
            set {
                if ((this.SoLuongDatField.Equals(value) != true)) {
                    this.SoLuongDatField = value;
                    this.RaisePropertyChanged("SoLuongDat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenSP {
            get {
                return this.TenSPField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSPField, value) != true)) {
                    this.TenSPField = value;
                    this.RaisePropertyChanged("TenSP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CTDHService.ICtDonDHService")]
    public interface ICtDonDHService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtDonDHService/HienThiCtDonDH", ReplyAction="http://tempuri.org/ICtDonDHService/HienThiCtDonDHResponse")]
        WebForm.CTDHService.CtDonDH[] HienThiCtDonDH(WebForm.CTDHService.CtDonDH ct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtDonDHService/HienThiCtDonDH", ReplyAction="http://tempuri.org/ICtDonDHService/HienThiCtDonDHResponse")]
        System.Threading.Tasks.Task<WebForm.CTDHService.CtDonDH[]> HienThiCtDonDHAsync(WebForm.CTDHService.CtDonDH ct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtDonDHService/Them", ReplyAction="http://tempuri.org/ICtDonDHService/ThemResponse")]
        void Them(WebForm.CTDHService.CtDonDH ct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtDonDHService/Them", ReplyAction="http://tempuri.org/ICtDonDHService/ThemResponse")]
        System.Threading.Tasks.Task ThemAsync(WebForm.CTDHService.CtDonDH ct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtDonDHService/Xoa", ReplyAction="http://tempuri.org/ICtDonDHService/XoaResponse")]
        void Xoa(WebForm.CTDHService.CtDonDH ct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtDonDHService/Xoa", ReplyAction="http://tempuri.org/ICtDonDHService/XoaResponse")]
        System.Threading.Tasks.Task XoaAsync(WebForm.CTDHService.CtDonDH ct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtDonDHService/Searid", ReplyAction="http://tempuri.org/ICtDonDHService/SearidResponse")]
        WebForm.CTDHService.CtDonDH Searid(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtDonDHService/Searid", ReplyAction="http://tempuri.org/ICtDonDHService/SearidResponse")]
        System.Threading.Tasks.Task<WebForm.CTDHService.CtDonDH> SearidAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICtDonDHServiceChannel : WebForm.CTDHService.ICtDonDHService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CtDonDHServiceClient : System.ServiceModel.ClientBase<WebForm.CTDHService.ICtDonDHService>, WebForm.CTDHService.ICtDonDHService {
        
        public CtDonDHServiceClient() {
        }
        
        public CtDonDHServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CtDonDHServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CtDonDHServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CtDonDHServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebForm.CTDHService.CtDonDH[] HienThiCtDonDH(WebForm.CTDHService.CtDonDH ct) {
            return base.Channel.HienThiCtDonDH(ct);
        }
        
        public System.Threading.Tasks.Task<WebForm.CTDHService.CtDonDH[]> HienThiCtDonDHAsync(WebForm.CTDHService.CtDonDH ct) {
            return base.Channel.HienThiCtDonDHAsync(ct);
        }
        
        public void Them(WebForm.CTDHService.CtDonDH ct) {
            base.Channel.Them(ct);
        }
        
        public System.Threading.Tasks.Task ThemAsync(WebForm.CTDHService.CtDonDH ct) {
            return base.Channel.ThemAsync(ct);
        }
        
        public void Xoa(WebForm.CTDHService.CtDonDH ct) {
            base.Channel.Xoa(ct);
        }
        
        public System.Threading.Tasks.Task XoaAsync(WebForm.CTDHService.CtDonDH ct) {
            return base.Channel.XoaAsync(ct);
        }
        
        public WebForm.CTDHService.CtDonDH Searid(int ID) {
            return base.Channel.Searid(ID);
        }
        
        public System.Threading.Tasks.Task<WebForm.CTDHService.CtDonDH> SearidAsync(int ID) {
            return base.Channel.SearidAsync(ID);
        }
    }
}
