//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForm.PhieuNhapServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhieuNhap", Namespace="http://schemas.datacontract.org/2004/07/WcfUngDungWeb")]
    [System.SerializableAttribute()]
    public partial class PhieuNhap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaPhieuNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgayNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NhaSX_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhieuNhap_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNhaSXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TongTienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaPhieuNhap {
            get {
                return this.MaPhieuNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.MaPhieuNhapField, value) != true)) {
                    this.MaPhieuNhapField = value;
                    this.RaisePropertyChanged("MaPhieuNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgayNhap {
            get {
                return this.NgayNhapField;
            }
            set {
                if ((this.NgayNhapField.Equals(value) != true)) {
                    this.NgayNhapField = value;
                    this.RaisePropertyChanged("NgayNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NhaSX_ID {
            get {
                return this.NhaSX_IDField;
            }
            set {
                if ((this.NhaSX_IDField.Equals(value) != true)) {
                    this.NhaSX_IDField = value;
                    this.RaisePropertyChanged("NhaSX_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhieuNhap_ID {
            get {
                return this.PhieuNhap_IDField;
            }
            set {
                if ((this.PhieuNhap_IDField.Equals(value) != true)) {
                    this.PhieuNhap_IDField = value;
                    this.RaisePropertyChanged("PhieuNhap_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNhaSX {
            get {
                return this.TenNhaSXField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNhaSXField, value) != true)) {
                    this.TenNhaSXField = value;
                    this.RaisePropertyChanged("TenNhaSX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TongTien {
            get {
                return this.TongTienField;
            }
            set {
                if ((this.TongTienField.Equals(value) != true)) {
                    this.TongTienField = value;
                    this.RaisePropertyChanged("TongTien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhieuNhapServiceReference1.IPhieuNhapService1")]
    public interface IPhieuNhapService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuNhapService1/HienThiPhieuNhap", ReplyAction="http://tempuri.org/IPhieuNhapService1/HienThiPhieuNhapResponse")]
        WinForm.PhieuNhapServiceReference1.PhieuNhap[] HienThiPhieuNhap();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuNhapService1/HienThiPhieuNhap", ReplyAction="http://tempuri.org/IPhieuNhapService1/HienThiPhieuNhapResponse")]
        System.Threading.Tasks.Task<WinForm.PhieuNhapServiceReference1.PhieuNhap[]> HienThiPhieuNhapAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuNhapService1/TimKiem", ReplyAction="http://tempuri.org/IPhieuNhapService1/TimKiemResponse")]
        WinForm.PhieuNhapServiceReference1.PhieuNhap[] TimKiem(WinForm.PhieuNhapServiceReference1.PhieuNhap pn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuNhapService1/TimKiem", ReplyAction="http://tempuri.org/IPhieuNhapService1/TimKiemResponse")]
        System.Threading.Tasks.Task<WinForm.PhieuNhapServiceReference1.PhieuNhap[]> TimKiemAsync(WinForm.PhieuNhapServiceReference1.PhieuNhap pn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuNhapService1/Them", ReplyAction="http://tempuri.org/IPhieuNhapService1/ThemResponse")]
        void Them(WinForm.PhieuNhapServiceReference1.PhieuNhap pn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuNhapService1/Them", ReplyAction="http://tempuri.org/IPhieuNhapService1/ThemResponse")]
        System.Threading.Tasks.Task ThemAsync(WinForm.PhieuNhapServiceReference1.PhieuNhap pn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuNhapService1/Sua_TongTien", ReplyAction="http://tempuri.org/IPhieuNhapService1/Sua_TongTienResponse")]
        void Sua_TongTien(WinForm.PhieuNhapServiceReference1.PhieuNhap pn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuNhapService1/Sua_TongTien", ReplyAction="http://tempuri.org/IPhieuNhapService1/Sua_TongTienResponse")]
        System.Threading.Tasks.Task Sua_TongTienAsync(WinForm.PhieuNhapServiceReference1.PhieuNhap pn);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhieuNhapService1Channel : WinForm.PhieuNhapServiceReference1.IPhieuNhapService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhieuNhapService1Client : System.ServiceModel.ClientBase<WinForm.PhieuNhapServiceReference1.IPhieuNhapService1>, WinForm.PhieuNhapServiceReference1.IPhieuNhapService1 {
        
        public PhieuNhapService1Client() {
        }
        
        public PhieuNhapService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhieuNhapService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhieuNhapService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhieuNhapService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WinForm.PhieuNhapServiceReference1.PhieuNhap[] HienThiPhieuNhap() {
            return base.Channel.HienThiPhieuNhap();
        }
        
        public System.Threading.Tasks.Task<WinForm.PhieuNhapServiceReference1.PhieuNhap[]> HienThiPhieuNhapAsync() {
            return base.Channel.HienThiPhieuNhapAsync();
        }
        
        public WinForm.PhieuNhapServiceReference1.PhieuNhap[] TimKiem(WinForm.PhieuNhapServiceReference1.PhieuNhap pn) {
            return base.Channel.TimKiem(pn);
        }
        
        public System.Threading.Tasks.Task<WinForm.PhieuNhapServiceReference1.PhieuNhap[]> TimKiemAsync(WinForm.PhieuNhapServiceReference1.PhieuNhap pn) {
            return base.Channel.TimKiemAsync(pn);
        }
        
        public void Them(WinForm.PhieuNhapServiceReference1.PhieuNhap pn) {
            base.Channel.Them(pn);
        }
        
        public System.Threading.Tasks.Task ThemAsync(WinForm.PhieuNhapServiceReference1.PhieuNhap pn) {
            return base.Channel.ThemAsync(pn);
        }
        
        public void Sua_TongTien(WinForm.PhieuNhapServiceReference1.PhieuNhap pn) {
            base.Channel.Sua_TongTien(pn);
        }
        
        public System.Threading.Tasks.Task Sua_TongTienAsync(WinForm.PhieuNhapServiceReference1.PhieuNhap pn) {
            return base.Channel.Sua_TongTienAsync(pn);
        }
    }
}
