//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForm.CtDonDHServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CtDonDHServiceReference.ICtDonDHService1")]
    public interface ICtDonDHService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtDonDHService1/DoWork", ReplyAction="http://tempuri.org/ICtDonDHService1/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtDonDHService1/DoWork", ReplyAction="http://tempuri.org/ICtDonDHService1/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICtDonDHService1Channel : WinForm.CtDonDHServiceReference.ICtDonDHService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CtDonDHService1Client : System.ServiceModel.ClientBase<WinForm.CtDonDHServiceReference.ICtDonDHService1>, WinForm.CtDonDHServiceReference.ICtDonDHService1 {
        
        public CtDonDHService1Client() {
        }
        
        public CtDonDHService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CtDonDHService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CtDonDHService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CtDonDHService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
