//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForm.CtDonDHServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CtDonDH", Namespace="http://schemas.datacontract.org/2004/07/WcfUngDungWeb")]
    [System.SerializableAttribute()]
    public partial class CtDonDH : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float DonGiaDatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaDonDHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SP_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoLuongDatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float DonGiaDat {
            get {
                return this.DonGiaDatField;
            }
            set {
                if ((this.DonGiaDatField.Equals(value) != true)) {
                    this.DonGiaDatField = value;
                    this.RaisePropertyChanged("DonGiaDat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaDonDH {
            get {
                return this.MaDonDHField;
            }
            set {
                if ((object.ReferenceEquals(this.MaDonDHField, value) != true)) {
                    this.MaDonDHField = value;
                    this.RaisePropertyChanged("MaDonDH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SP_ID {
            get {
                return this.SP_IDField;
            }
            set {
                if ((this.SP_IDField.Equals(value) != true)) {
                    this.SP_IDField = value;
                    this.RaisePropertyChanged("SP_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuongDat {
            get {
                return this.SoLuongDatField;
            }
            set {
                if ((this.SoLuongDatField.Equals(value) != true)) {
                    this.SoLuongDatField = value;
                    this.RaisePropertyChanged("SoLuongDat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenSP {
            get {
                return this.TenSPField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSPField, value) != true)) {
                    this.TenSPField = value;
                    this.RaisePropertyChanged("TenSP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CtDonDHServiceReference.ICtDonDHService1")]
    public interface ICtDonDHService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtDonDHService1/HienThiCtDonDH", ReplyAction="http://tempuri.org/ICtDonDHService1/HienThiCtDonDHResponse")]
        WinForm.CtDonDHServiceReference.CtDonDH[] HienThiCtDonDH(WinForm.CtDonDHServiceReference.CtDonDH ct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtDonDHService1/HienThiCtDonDH", ReplyAction="http://tempuri.org/ICtDonDHService1/HienThiCtDonDHResponse")]
        System.Threading.Tasks.Task<WinForm.CtDonDHServiceReference.CtDonDH[]> HienThiCtDonDHAsync(WinForm.CtDonDHServiceReference.CtDonDH ct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtDonDHService1/Them", ReplyAction="http://tempuri.org/ICtDonDHService1/ThemResponse")]
        void Them(WinForm.CtDonDHServiceReference.CtDonDH ct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtDonDHService1/Them", ReplyAction="http://tempuri.org/ICtDonDHService1/ThemResponse")]
        System.Threading.Tasks.Task ThemAsync(WinForm.CtDonDHServiceReference.CtDonDH ct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtDonDHService1/Xoa", ReplyAction="http://tempuri.org/ICtDonDHService1/XoaResponse")]
        void Xoa(WinForm.CtDonDHServiceReference.CtDonDH ct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICtDonDHService1/Xoa", ReplyAction="http://tempuri.org/ICtDonDHService1/XoaResponse")]
        System.Threading.Tasks.Task XoaAsync(WinForm.CtDonDHServiceReference.CtDonDH ct);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICtDonDHService1Channel : WinForm.CtDonDHServiceReference.ICtDonDHService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CtDonDHService1Client : System.ServiceModel.ClientBase<WinForm.CtDonDHServiceReference.ICtDonDHService1>, WinForm.CtDonDHServiceReference.ICtDonDHService1 {
        
        public CtDonDHService1Client() {
        }
        
        public CtDonDHService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CtDonDHService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CtDonDHService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CtDonDHService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WinForm.CtDonDHServiceReference.CtDonDH[] HienThiCtDonDH(WinForm.CtDonDHServiceReference.CtDonDH ct) {
            return base.Channel.HienThiCtDonDH(ct);
        }
        
        public System.Threading.Tasks.Task<WinForm.CtDonDHServiceReference.CtDonDH[]> HienThiCtDonDHAsync(WinForm.CtDonDHServiceReference.CtDonDH ct) {
            return base.Channel.HienThiCtDonDHAsync(ct);
        }
        
        public void Them(WinForm.CtDonDHServiceReference.CtDonDH ct) {
            base.Channel.Them(ct);
        }
        
        public System.Threading.Tasks.Task ThemAsync(WinForm.CtDonDHServiceReference.CtDonDH ct) {
            return base.Channel.ThemAsync(ct);
        }
        
        public void Xoa(WinForm.CtDonDHServiceReference.CtDonDH ct) {
            base.Channel.Xoa(ct);
        }
        
        public System.Threading.Tasks.Task XoaAsync(WinForm.CtDonDHServiceReference.CtDonDH ct) {
            return base.Channel.XoaAsync(ct);
        }
    }
}
