'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CT_DonDH
    Public Property MaDonDH As String
    Public Property SP_ID As Integer
    Public Property DonGiaDat As Double
    Public Property SoLuongDat As Integer

    Public Overridable Property DonDH As DonDH
    Public Overridable Property SanPham As SanPham

End Class
