'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CT_PhieuNhap
    Public Property MaPhieuNhap As String
    Public Property SP_ID As Integer
    Public Property SoLuongNhap As Integer
    Public Property DonGiaNhap As Double

    Public Overridable Property PhieuNhap As PhieuNhap
    Public Overridable Property SanPham As SanPham

End Class
