'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CT_PhieuXuat
    Public Property MaPhieuXuat As String
    Public Property SP_ID As Integer
    Public Property SoLuongXuat As Integer
    Public Property DonGiaXuat As Double

    Public Overridable Property PhieuXuat As PhieuXuat
    Public Overridable Property SanPham As SanPham

End Class
