'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DonDH
    Public Property DonDH_ID As Integer
    Public Property MaDonDH As String
    Public Property HoTenKH As String
    Public Property DiaChi As String
    Public Property DienThoai As String
    Public Property Email As String
    Public Property NgayDat As Date
    Public Property NgayGiao As Date
    Public Property GhiChu As String
    Public Property TinhTrang As String
    Public Property TongTien As Double
    Public Property ID_NguoiDung As Nullable(Of Integer)

    Public Overridable Property CT_DonDH As ICollection(Of CT_DonDH) = New HashSet(Of CT_DonDH)

End Class
