'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NguoiDung
    Public Property ID As Integer
    Public Property Ten As String
    Public Property TenDangNhap As String
    Public Property MatKhau As String
    Public Property Email As String
    Public Property Quyen As Integer
    Public Property DiaChi As String
    Public Property SoDienThoai As String

End Class
