'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NhaSX
    Public Property NhaSX_ID As Integer
    Public Property TenNhaSX As String

    Public Overridable Property PhieuNhaps As ICollection(Of PhieuNhap) = New HashSet(Of PhieuNhap)
    Public Overridable Property SanPhams As ICollection(Of SanPham) = New HashSet(Of SanPham)

End Class
