'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PhieuXuat
    Public Property PhieuXuat_ID As Integer
    Public Property MaPhieuXuat As String
    Public Property MaDonDH As String
    Public Property NgayXuat As Date

    Public Overridable Property CT_PhieuXuat As ICollection(Of CT_PhieuXuat) = New HashSet(Of CT_PhieuXuat)

End Class
