'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class XDPM_WebsiteEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=XDPM_WebsiteEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property CT_DonDH() As DbSet(Of CT_DonDH)
    Public Overridable Property CT_PhieuNhap() As DbSet(Of CT_PhieuNhap)
    Public Overridable Property CT_PhieuXuat() As DbSet(Of CT_PhieuXuat)
    Public Overridable Property DonDHs() As DbSet(Of DonDH)
    Public Overridable Property NhaSXes() As DbSet(Of NhaSX)
    Public Overridable Property PhieuNhaps() As DbSet(Of PhieuNhap)
    Public Overridable Property PhieuXuats() As DbSet(Of PhieuXuat)
    Public Overridable Property SanPhams() As DbSet(Of SanPham)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)
    Public Overridable Property TonKhoes() As DbSet(Of TonKho)
    Public Overridable Property NguoiDungs() As DbSet(Of NguoiDung)

End Class
