'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SanPham
    Public Property SP_ID As Integer
    Public Property TenSP As String
    Public Property NhaSX_ID As Integer
    Public Property CPU As String
    Public Property RAM As String
    Public Property HDD As String
    Public Property BaoHanh As String
    Public Property DonGia As Double
    Public Property Hinh As String
    Public Property MoTa As String

    Public Overridable Property CT_DonDH As ICollection(Of CT_DonDH) = New HashSet(Of CT_DonDH)
    Public Overridable Property CT_PhieuNhap As ICollection(Of CT_PhieuNhap) = New HashSet(Of CT_PhieuNhap)
    Public Overridable Property CT_PhieuXuat As ICollection(Of CT_PhieuXuat) = New HashSet(Of CT_PhieuXuat)
    Public Overridable Property NhaSX As NhaSX
    Public Overridable Property TonKhoes As ICollection(Of TonKho) = New HashSet(Of TonKho)

End Class
