//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForm.TonKhoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TonKhoServiceReference.ITonKhoService1")]
    public interface ITonKhoService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITonKhoService1/DoWork", ReplyAction="http://tempuri.org/ITonKhoService1/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITonKhoService1/DoWork", ReplyAction="http://tempuri.org/ITonKhoService1/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITonKhoService1Channel : WinForm.TonKhoServiceReference.ITonKhoService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TonKhoService1Client : System.ServiceModel.ClientBase<WinForm.TonKhoServiceReference.ITonKhoService1>, WinForm.TonKhoServiceReference.ITonKhoService1 {
        
        public TonKhoService1Client() {
        }
        
        public TonKhoService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TonKhoService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TonKhoService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TonKhoService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
