//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForm.NguoiDungServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NguoiDungServiceReference.INguoiDungService1")]
    public interface INguoiDungService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguoiDungService1/DoWork", ReplyAction="http://tempuri.org/INguoiDungService1/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguoiDungService1/DoWork", ReplyAction="http://tempuri.org/INguoiDungService1/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INguoiDungService1Channel : WinForm.NguoiDungServiceReference.INguoiDungService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NguoiDungService1Client : System.ServiceModel.ClientBase<WinForm.NguoiDungServiceReference.INguoiDungService1>, WinForm.NguoiDungServiceReference.INguoiDungService1 {
        
        public NguoiDungService1Client() {
        }
        
        public NguoiDungService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NguoiDungService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NguoiDungService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NguoiDungService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
